/**
 * @fileoverview gRPC-Web generated client stub for pb
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.19.1
// source: exist_crud.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as exist_crud_msg_pb from './exist_crud_msg_pb';
import * as person_info_msg_pb from './person_info_msg_pb';


export class ExistCRUDServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorAddNewPerson = new grpcWeb.MethodDescriptor(
    '/pb.ExistCRUDService/AddNewPerson',
    grpcWeb.MethodType.UNARY,
    person_info_msg_pb.PersonInfoRequest,
    exist_crud_msg_pb.Response,
    (request: person_info_msg_pb.PersonInfoRequest) => {
      return request.serializeBinary();
    },
    exist_crud_msg_pb.Response.deserializeBinary
  );

  addNewPerson(
    request: person_info_msg_pb.PersonInfoRequest,
    metadata: grpcWeb.Metadata | null): Promise<exist_crud_msg_pb.Response>;

  addNewPerson(
    request: person_info_msg_pb.PersonInfoRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: exist_crud_msg_pb.Response) => void): grpcWeb.ClientReadableStream<exist_crud_msg_pb.Response>;

  addNewPerson(
    request: person_info_msg_pb.PersonInfoRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: exist_crud_msg_pb.Response) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.ExistCRUDService/AddNewPerson',
        request,
        metadata || {},
        this.methodDescriptorAddNewPerson,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.ExistCRUDService/AddNewPerson',
    request,
    metadata || {},
    this.methodDescriptorAddNewPerson);
  }

  methodDescriptorUpdatePersonInfo = new grpcWeb.MethodDescriptor(
    '/pb.ExistCRUDService/UpdatePersonInfo',
    grpcWeb.MethodType.UNARY,
    person_info_msg_pb.EditPersonInfoParameters,
    exist_crud_msg_pb.Response,
    (request: person_info_msg_pb.EditPersonInfoParameters) => {
      return request.serializeBinary();
    },
    exist_crud_msg_pb.Response.deserializeBinary
  );

  updatePersonInfo(
    request: person_info_msg_pb.EditPersonInfoParameters,
    metadata: grpcWeb.Metadata | null): Promise<exist_crud_msg_pb.Response>;

  updatePersonInfo(
    request: person_info_msg_pb.EditPersonInfoParameters,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: exist_crud_msg_pb.Response) => void): grpcWeb.ClientReadableStream<exist_crud_msg_pb.Response>;

  updatePersonInfo(
    request: person_info_msg_pb.EditPersonInfoParameters,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: exist_crud_msg_pb.Response) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.ExistCRUDService/UpdatePersonInfo',
        request,
        metadata || {},
        this.methodDescriptorUpdatePersonInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.ExistCRUDService/UpdatePersonInfo',
    request,
    metadata || {},
    this.methodDescriptorUpdatePersonInfo);
  }

  methodDescriptorFindPersonInfo = new grpcWeb.MethodDescriptor(
    '/pb.ExistCRUDService/FindPersonInfo',
    grpcWeb.MethodType.UNARY,
    person_info_msg_pb.NationalIDNumber,
    person_info_msg_pb.PersonInfoResponse,
    (request: person_info_msg_pb.NationalIDNumber) => {
      return request.serializeBinary();
    },
    person_info_msg_pb.PersonInfoResponse.deserializeBinary
  );

  findPersonInfo(
    request: person_info_msg_pb.NationalIDNumber,
    metadata: grpcWeb.Metadata | null): Promise<person_info_msg_pb.PersonInfoResponse>;

  findPersonInfo(
    request: person_info_msg_pb.NationalIDNumber,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: person_info_msg_pb.PersonInfoResponse) => void): grpcWeb.ClientReadableStream<person_info_msg_pb.PersonInfoResponse>;

  findPersonInfo(
    request: person_info_msg_pb.NationalIDNumber,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: person_info_msg_pb.PersonInfoResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/pb.ExistCRUDService/FindPersonInfo',
        request,
        metadata || {},
        this.methodDescriptorFindPersonInfo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/pb.ExistCRUDService/FindPersonInfo',
    request,
    metadata || {},
    this.methodDescriptorFindPersonInfo);
  }

}

