import { StyleSheet } from "aphrodite/no-important";


const styles = StyleSheet.create({
  root: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: "rgb(255,255,255)",
    borderRadius: "20px 20px 20px 20px",
    position: "relative",
    overflow: "hidden",
    minHeight: 520,
  },
  decorator: {
    width: 933,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 44,
    right: -11,
  },
  image2: {
    width: 112,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    bottom: 66,
    right: 180,
  },
  content_box: {
    width: 109,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    bottom: 45,
    right: 49,
  },
  image3: {
    width: 926,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 179,
    right: 0,
  },
  highlights1: {
    font: '400 15px/1.2 "Inter", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    letterSpacing: "0px",
    position: "absolute",
    top: 17,
    height: 52,
    left: 25,
    width: 142,
  },
  highlights1_span0: {
    font: '1em/1.2 "Inter", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    fontStyle: "normal",
    letterSpacing: "0px",
  },
  highlights1_span1: {
    font: '0.9333333333333333em/1.28 "Inter", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    fontStyle: "normal",
    letterSpacing: "0px",
  },
  decorator4: {
    width: 899,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: -28,
    left: 4,
  },
  decorator3: {
    width: 919,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    bottom: -21,
    right: -12,
  },
  group: {
    display: "flex",
    flexDirection: "column",
    width: 597,
    height: 530,
    position: "absolute",
    top: 0,
    left: -84,
  },
  decorator1: {
    width: 597,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 0,
    right: 0,
  },
  decorator2: {
    width: 296,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 100,
    left: 100,
  },
  col: {
    display: "flex",
    flexDirection: "column",
    width: "62.88%",
    position: "relative",
    flexGrow: 1,
    margin: "354px 36.16% 27px 0.97%",
  },
  col__item: {
    display: "flex",
    flexDirection: "column",
    position: "relative",
  },
  content_box1: {
    width: "100%",
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "relative",
  },
  highlights11: {
    font: '400 15px/1.2 "Inter", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    letterSpacing: "0px",
    width: "86.01%",
    position: "relative",
    margin: "21px auto 0px",
  },
  content_box2: {
    display: "flex",
    flexDirection: "column",
    background: "var(--src) center center / cover no-repeat",
    width: 446,
    height: 39,
    position: "absolute",
    top: 221,
    right: 109,
  },
  row: {
    display: "flex",
    position: "relative",
    flexGrow: 1,
    margin: "5.5px 4px 4.5px",
  },
  highlights12: {
    font: '400 15px/1.2 "Inter", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    letterSpacing: "0px",
    position: "relative",
    flex: "0 0 auto",
    minWidth: 268,
    margin: "0px 0px 11px",
  },
  row__spacer: {
    flex: "0 1 34px",
  },
  desc: {
    font: '400 10px/1.2 "Inter", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    letterSpacing: "0px",
    position: "relative",
    flex: "1 1 113px",
  },
  desc_span0: {
    font: '1em/1.2 "Inter", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    fontStyle: "normal",
    letterSpacing: "0px",
  },
  desc_span1: {
    font: '1.5em/1.2 "Inter", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    fontStyle: "normal",
    letterSpacing: "0px",
  },
  desc_span2: {
    font: '1em/1.2 "Inter", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    fontStyle: "normal",
    letterSpacing: "0px",
  },
});


export default styles;