import { StyleSheet } from "aphrodite/no-important";

const styles = StyleSheet.create({
  root: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: "rgb(255,255,255)",
    borderRadius: "20px 20px 20px 20px",
    position: "relative",
    overflow: "hidden",
  },
  decorator8: {
    width: 917,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    bottom: 0,
    right: 0,
  },
  rect1: {
    width: 150,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    bottom: 44,
    right: 2,
  },
  image4: {
    width: 67,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 10,
    right: 21,
  },
  decorator2: {
    width: 611,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 0,
    left: 0,
  },
  decorator: {
    width: 615,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 91,
    left: 0,
  },
  image: {
    width: 204,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    bottom: 37,
    right: 141,
  },
  decorator5: {
    width: 352,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 32,
    left: 278,
  },
  decorator3: {
    width: 485,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 10,
    right: 0,
  },
  decorator6: {
    width: 932,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 116,
    right: 0,
  },
  image1: {
    width: 717,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 13,
    right: 2,
  },
  decorator4: {
    width: 620,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 0,
    right: 22,
  },
  decorator7: {
    width: 906,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 104,
    left: 0,
  },
  decorator1: {
    width: 279,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 0,
    left: 47,
  },
  row: {
    display: "flex",
    width: 681,
    height: 67,
    position: "absolute",
    top: 10,
    left: 28,
  },
  row__item: {
    display: "flex",
    flexDirection: "column",
    position: "relative",
    flex: "0 1 86px",
  },
  image5: {
    borderRadius: "20px 5px 5px 5px",
    width: 86,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "relative",
    minWidth: 86,
    margin: "8px 0px 0px",
  },
  row__spacer: {
    flex: "0 1 15px",
  },
  col: {
    display: "flex",
    flexDirection: "column",
    position: "relative",
    flex: "0 1 580px",
  },
  big_title: {
    font: '400 35px/1.37 "Alata", Helvetica, Arial, serif',
    color: "rgb(2,45,70)",
    letterSpacing: "0px",
    position: "relative",
  },
  content_box1: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: "rgba(181,8,8,0.49)",
    width: "44.83%",
    height: 19,
    position: "relative",
    margin: "0px 55.17% 0px 0%",
  },
  highlights1: {
    font: '400 18px/1.27 "Alatsi", Helvetica, Arial, serif',
    color: "rgb(255,255,255)",
    letterSpacing: "0px",
    width: 218,
    height: 23,
    position: "absolute",
    top: -4,
    left: 12,
  },
  group: {
    display: "flex",
    flexDirection: "column",
    width: 248,
    height: 380,
    position: "absolute",
    top: 96,
    left: 28,
  },
  image2: {
    width: 248,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 0,
    right: 0,
  },
  group1: {
    display: "flex",
    flexDirection: "column",
    width: 190,
    height: 359,
    position: "absolute",
    top: 23,
    right: -225,
  },
  col1: {
    display: "flex",
    flexDirection: "column",
    width: 234,
    height: 42,
    position: "absolute",
    top: 152,
    right: -271,
  },
  highlights: {
    font: '400 16px/1 "Aldrich", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    letterSpacing: "0px",
    position: "relative",
  },
  highlights3: {
    font: '400 18px/1.38 "Alef", Helvetica, Arial, serif',
    color: "rgb(65,92,189)",
    letterSpacing: "0px",
    position: "relative",
    margin: "1px 0px 0px",
  },
  content_box11: {
    display: "flex",
    flexDirection: "column",
    backgroundColor: "rgb(17,112,165)",
    width: 335,
    height: 34,
    position: "absolute",
    top: 10,
    right: -431,
  },
  content_box: {
    display: "flex",
    flexDirection: "column",
    background: "var(--src) center center / cover no-repeat",
    position: "relative",
    flexGrow: 1,
  },
  highlights4: {
    font: '400 18px/1 "Aldrich", Helvetica, Arial, serif',
    color: "rgb(255,255,255)",
    letterSpacing: "0px",
    width: "44.78%",
    position: "relative",
    flexGrow: 1,
    margin: "8px 23.88% 8px 31.34%",
  },
  col2: {
    display: "flex",
    flexDirection: "column",
    width: 190,
    height: 359,
    position: "absolute",
    top: 0,
    right: 0,
  },
  col3: {
    display: "flex",
    flexDirection: "column",
    position: "relative",
  },
  highlights2: {
    font: '400 16px/1 "Aldrich", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    letterSpacing: "0px",
    position: "relative",
    margin: "0px 5px",
  },
  highlights31: {
    font: '400 18px/1.38 "Alef", Helvetica, Arial, serif',
    color: "rgb(65,92,189)",
    letterSpacing: "0px",
    position: "relative",
    margin: "4px 14px 0px",
  },
  highlights5: {
    font: '400 16px/1 "Aldrich", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    letterSpacing: "0px",
    position: "relative",
    margin: "8px 0px 0px 5px",
  },
  highlights32: {
    font: '400 18px/1.38 "Alef", Helvetica, Arial, serif',
    color: "rgb(65,92,189)",
    letterSpacing: "0px",
    position: "relative",
    margin: "4px 15px 0px",
  },
  highlights6: {
    font: '400 16px/1 "Aldrich", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    letterSpacing: "0px",
    position: "relative",
    margin: "4px 22px 0px 5px",
  },
  highlights33: {
    font: '400 18px/1.38 "Alef", Helvetica, Arial, serif',
    color: "rgb(65,92,189)",
    letterSpacing: "0px",
    position: "relative",
    margin: "5px 14px 0px",
  },
  highlights21: {
    font: '400 15px/1 "Aldrich", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    letterSpacing: "0px",
    position: "relative",
    margin: "4px 0px 0px",
  },
  row1: {
    display: "flex",
    position: "relative",
    margin: "20px 0px 0px",
  },
  text: {
    font: '400 14px/1 "Aldrich", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    letterSpacing: "0px",
    position: "relative",
    flex: "0 0 auto",
    minWidth: 25,
    margin: "3px 0px 30px",
  },
  desc: {
    font: '12px/1.33 "Alef", Helvetica, Arial, serif',
    color: "rgb(29,9,9)",
    letterSpacing: "0px",
    opacity: 0.69,
    position: "relative",
    flex: "1 1 138px",
    margin: "0px 0px 0px 8px",
  },
  col4: {
    display: "flex",
    flexDirection: "column",
    position: "relative",
    margin: "9px 7px 0px 0px",
  },
  text1: {
    font: '14px/1 "Aldrich", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    letterSpacing: "0px",
    position: "relative",
    margin: "0px 34px 0px 0px",
  },
  text2: {
    font: '14px/1 "Aldrich", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    letterSpacing: "0px",
    position: "relative",
    margin: "13px 0px 0px",
  },
  col5: {
    display: "flex",
    flexDirection: "column",
    width: 81,
    position: "relative",
    minWidth: 81,
    margin: "15px 0px 0px",
  },
  row2: {
    display: "flex",
    position: "relative",
  },
  info: {
    font: '400 12px/1.33 "Alegreya", Helvetica, Arial, serif',
    color: "rgb(222,24,24)",
    letterSpacing: "0px",
    position: "relative",
    flex: "0 0 auto",
    minWidth: 20,
    margin: "1px 0px 0px",
  },
  info2: {
    font: '400 12px/1.33 "Alegreya", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    letterSpacing: "0px",
    position: "relative",
    flex: "0 0 auto",
    minWidth: 54,
    margin: "0px 0px 1px 7px",
  },
  info1: {
    font: '400 12px/1.33 "Alegreya", Helvetica, Arial, serif',
    color: "rgb(222,24,24)",
    letterSpacing: "0px",
    position: "relative",
    flex: "0 0 auto",
    minWidth: 25,
  },
  info21: {
    font: '400 12px/1.33 "Alegreya", Helvetica, Arial, serif',
    color: "rgb(0,0,0)",
    letterSpacing: "0px",
    position: "relative",
    flex: "0 0 auto",
    minWidth: 52,
    margin: "0px 0px 3px 2px",
  },
  image3: {
    width: 93,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 322,
    right: 20,
  },
  cover: {
    width: 385,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "absolute",
    top: 113,
    right: 188,
  },
  image6: {
    width: 0,
    height: "auto",
    verticalAlign: "top",
    objectFit: "contain",
    objectPosition: "center top",
    position: "relative",
    minWidth: 0,
    margin: "372px auto 132px",
  },
});

export default styles;